FROM node:21.3.0-alpine as build
WORKDIR /usr/local/app
COPY . .
RUN npm install
RUN npm run build

FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/nginx.conf
COPY --from=build /usr/local/app/dist/frontend /usr/share/nginx/html

EXPOSE 80